/**
 * Root `AGENTS.md` (REQ-KRN-033, ADR-0022 п. 2, 5): the text of every path rule
 * with `paths: ["**"]`, packs and `.warrant/local/rules/` alike, in id order,
 * under the generated marker. An exact-bytes target of the `sync` plan.
 */
import { cliError, type CliError } from "../errors.js";
import type { LoadedRule } from "../packs/types.js";

export const AGENTS_MD_REL = "AGENTS.md";

/** First line of the file (ADR-0022 п. 5). */
export const AGENTS_MD_MARKER = "<!-- generated by warrant — do not edit -->";

/** Largest `AGENTS.md` in bytes: half the budget of Codex (ADR-0022 п. 5). */
export const AGENTS_MD_LIMIT = 16 * 1024;

/** Rules delivered through `AGENTS.md`: those whose `paths` is exactly `["**"]`. */
export function generalRules(rules: readonly LoadedRule[]): LoadedRule[] {
  return rules
    .filter((rule) => rule.paths.length === 1 && rule.paths[0] === "**")
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

/**
 * Bytes of `AGENTS.md`: the marker, then each rule text as its own paragraph
 * (a blank line before it, trailing blank space trimmed). Undefined when no
 * rule qualifies — the file is then not generated; an error above the limit.
 */
export function agentsMd(rules: readonly LoadedRule[]): { bytes: Buffer } | { error: CliError } | undefined {
  const general = generalRules(rules);
  if (general.length === 0) return undefined;
  const text = [AGENTS_MD_MARKER, ...general.map((rule) => `\n${rule.text.trimEnd()}`)].join("\n") + "\n";
  const bytes = Buffer.from(text, "utf8");
  if (bytes.length > AGENTS_MD_LIMIT) {
    return {
      error: cliError(
        "GENERATED_TOO_LARGE",
        `${AGENTS_MD_REL} would be ${bytes.length} bytes, more than ${AGENTS_MD_LIMIT} (16 KiB)`,
        {
          path: AGENTS_MD_REL,
          hint: 'shorten the rules with paths ["**"] or narrow their paths, then run `warrant sync`'
        }
      )
    };
  }
  return { bytes };
}
