/**
 * Form of the WARRANT development hooks (ADR-0029 п. 6, 7, ADR-0031, ADR-0032 п. 11): the committed
 * `.claude/settings.json` holds only `$schema` and `hooks`; the only events are `SubagentStart`, `PreToolUse`,
 * `PostToolUse` and `SessionStart`; every hook command is `node "${CLAUDE_PROJECT_DIR}/scripts/dev/<script>.js" <event>`
 * from the white list — `cs-hook.js` for the first three (code-search), `git-hook.js` for `PreToolUse` on Bash /
 * PowerShell (ADR-0033 п. 9: git in the main checkout, force push, `openspec archive`; its rules are pinned here),
 * `brief.js` for `SessionStart` (session state, all sources: no matcher). No permissions, no statusline, no graft's own
 * hooks (ADR-0026 п. 2, ADR-0023). Hooks in the frontmatter of `.claude/agents/*.md` — only the guard of the review Run
 * in `warrant-reviewer.md` (design phase-4b §6, I-168): it acts only inside that subagent, the main session stays
 * without guard (ADR-0034 п. 4).
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { parse as parseYaml } from "yaml";

import { RULES } from "../../../../../scripts/dev/git-hook-lib.js";
import { CLI_ROOT } from "../../helpers/cli.js";

const REPO_ROOT = path.resolve(CLI_ROOT, "..", "..");
const SETTINGS = path.join(REPO_ROOT, ".claude", "settings.json");
const COMMAND = /^node "\$\{CLAUDE_PROJECT_DIR\}\/scripts\/dev\/([a-z-]+\.js)" ([a-z-]+)$/;
/** White list (ADR-0032 п. 11, ADR-0033 п. 9): event → scripts and their argument. */
const WHITE_LIST: Record<string, { script: string; arg: string }[]> = {
  SubagentStart: [{ script: "cs-hook.js", arg: "subagent-start" }],
  PreToolUse: [
    { script: "cs-hook.js", arg: "pre-tool" },
    { script: "git-hook.js", arg: "pre-tool" },
  ],
  PostToolUse: [{ script: "cs-hook.js", arg: "post-tool" }],
  SessionStart: [{ script: "brief.js", arg: "session-start" }],
};
/** White list of hooks in the frontmatter of agents: file → `hooks` (design phase-4b §6, generated by `warrant sync`). */
const AGENT_HOOKS: Record<string, unknown> = {
  "warrant-reviewer.md": {
    PreToolUse: [
      {
        matcher: "Bash|Write",
        hooks: [{ type: "command", command: 'node "${CLAUDE_PROJECT_DIR:-.}/packages/cli/dist/bin/warrant.js" guard --frontend claude' }]
      }
    ]
  },
};
/** Commands the git hook decides on — exactly ADR-0033 п. 9 and ADR-0043; a new rule is a new decision, not a quiet addition. */
const GIT_HOOK_RULES = ["force-push", "long-command", "main-checkout", "openspec-archive"];

interface HookGroup {
  matcher?: string;
  hooks: { type: string; command: string; timeout?: number }[];
}

const settings = JSON.parse(readFileSync(SETTINGS, "utf8")) as { hooks: Record<string, HookGroup[]> } & Record<string, unknown>;

describe(".claude/settings.json — development hooks only", () => {
  it("has only $schema and hooks", () => {
    expect(Object.keys(settings).sort()).toEqual(["$schema", "hooks"]);
  });

  it("uses only SubagentStart, PreToolUse, PostToolUse and SessionStart", () => {
    expect(Object.keys(settings.hooks).sort()).toEqual(["PostToolUse", "PreToolUse", "SessionStart", "SubagentStart"]);
  });

  it("every hook runs the white-listed scripts/dev script with the event of its section", () => {
    for (const [event, groups] of Object.entries(settings.hooks)) {
      for (const group of groups) {
        for (const hook of group.hooks) {
          expect(hook.type).toBe("command");
          const m = COMMAND.exec(hook.command);
          expect(m, hook.command).not.toBeNull();
          expect(WHITE_LIST[event], `${event}: ${hook.command}`).toContainEqual({ script: m?.[1], arg: m?.[2] });
          expect(hook.timeout ?? 600).toBeLessThanOrEqual(30);
        }
      }
    }
  });

  it("PostToolUse watches only reading and searching tools", () => {
    const matchers = settings.hooks.PostToolUse!.map((g) => g.matcher);
    expect(matchers).toEqual(["Read|Grep|Glob|Bash|PowerShell"]);
  });

  it("PreToolUse (deny): cs-hook sees only the tools the detector can flag (ADR-0031), git-hook only shells (ADR-0033)", () => {
    const groups = settings.hooks.PreToolUse!.map((g) => [g.matcher, COMMAND.exec(g.hooks[0]!.command)?.[1]]);
    expect(groups).toEqual([
      ["Read|Grep|Bash|PowerShell", "cs-hook.js"],
      ["Bash|PowerShell", "git-hook.js"],
    ]);
  });

  it("git-hook decides exactly the commands of ADR-0033 п. 9", () => {
    expect(Object.keys(RULES).sort()).toEqual(GIT_HOOK_RULES);
  });

  it("SessionStart has no matcher — the state comes back on startup, resume, clear and compact (ADR-0032 п. 4)", () => {
    const groups = settings.hooks.SessionStart!;
    expect(groups).toHaveLength(1);
    expect(groups[0]!.matcher).toBeUndefined();
  });

  it("the hook scripts exist", () => {
    for (const script of ["cs-hook.js", "git-hook.js", "brief.js"]) {
      expect(existsSync(path.join(REPO_ROOT, "scripts", "dev", script)), script).toBe(true);
    }
  });
});

describe(".claude/agents — hooks in the frontmatter", () => {
  it("only warrant-reviewer carries hooks: the guard of the review Run on Bash", () => {
    const dir = path.join(REPO_ROOT, ".claude", "agents");
    const found: Record<string, unknown> = {};
    for (const name of readdirSync(dir).filter((n) => n.endsWith(".md")).sort()) {
      const text = readFileSync(path.join(dir, name), "utf8").replace(/\r\n/g, "\n");
      const match = /^---\n([\s\S]*?)\n---\n/.exec(text);
      const keys = (match === null ? {} : parseYaml(match[1] ?? "")) as Record<string, unknown>;
      if (keys["hooks"] !== undefined) found[name] = keys["hooks"];
    }
    expect(found).toEqual(AGENT_HOOKS);
  });
});
