/**
 * Form of Markdown in the repository (ADR-0046): a paragraph and a list item are one line — no line breaks by width,
 * no hard breaks, no ordered list glued to a paragraph; a place is addressed by id → section → file, never by a line
 * number `file.md:N`. The detector is `scripts/dev/md-form-lib.js`; this file walks the Markdown of the repository.
 * `PENDING` is a ratchet: paths of profile `factory-change` that only Change `md-format` may clean — the Change
 * removes its line, and a clean path left in the list fails the test. `## Purpose` of a main spec is out of the rule:
 * archive keeps it as is (OpenSpec `specs-apply`), and main specs change only through archive (ADR-0011).
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { lineAddresses, wrapFindings } from "../../../../../scripts/dev/md-form-lib.js";
import { CLI_ROOT } from "../../helpers/cli.js";

const REPO_ROOT = path.resolve(CLI_ROOT, "..", "..");

/** Roots of the Markdown of the repository. */
const ROOTS = ["CLAUDE.md", "README.md", ".claude", "docs", "lattice", "openspec", "packages", "packs", "sra"];
/** Never walked: dependencies, build output, local state. */
const SKIP_DIRS = new Set(["node_modules", "dist", ".obsidian", ".git"]);
/** Not under the rule, with the reason: frozen history, text of other tools, test data. */
const NOT_OURS: [string, string][] = [
  ["openspec/changes/archive/", "an archived Change is immutable (ADR-0021)"],
  ["docs/archive/", "history, not edited"],
  [".claude/skills/openspec-", "generated by OpenSpec (ADR-0015 п. 6)"],
  ["packages/cli/test/fixtures/", "test data, compared as is"],
];
/** Under the rule, not clean yet: policy paths of `factory-change` — Change `md-format` (ADR-0046 п. 4). */
const PENDING = ["openspec/specs/", "sra/skills/", ".claude/agents/warrant-reviewer.md", "packs/core-sdd/golden/"];

function walk(rel: string): string[] {
  const abs = path.join(REPO_ROOT, rel);
  if (!existsSync(abs)) return [];
  if (rel.endsWith(".md")) return [rel];
  const out: string[] = [];
  for (const e of readdirSync(abs, { withFileTypes: true })) {
    if (SKIP_DIRS.has(e.name)) continue;
    const child = `${rel}/${e.name}`;
    if (e.isDirectory()) out.push(...walk(child));
    else if (e.name.endsWith(".md")) out.push(child);
  }
  return out;
}

const all = ROOTS.flatMap(walk).filter((p) => !NOT_OURS.some(([prefix]) => p.startsWith(prefix)));
const read = (p: string) => readFileSync(path.join(REPO_ROOT, p), "utf8");

/** Lines of `## Purpose` of a main spec: `openspec archive` carries it over as is, a delta cannot change it. */
function purposeLines(p: string, text: string): Set<number> {
  const out = new Set<number>();
  if (!p.startsWith("openspec/specs/")) return out;
  let inPurpose = false;
  text.split(/\r?\n/).forEach((line, i) => {
    if (/^## /.test(line)) inPurpose = line.trim() === "## Purpose";
    else if (inPurpose) out.add(i + 1);
  });
  return out;
}

const wraps = (p: string) => {
  const text = read(p);
  const kept = purposeLines(p, text);
  return wrapFindings(text)
    .filter((f) => !kept.has(f.line))
    .map((f) => `${p}:${f.line} ${f.kind}`);
};

describe("Markdown form — ADR-0046", () => {
  it("walks the Markdown of the repository", () => {
    expect(all.length).toBeGreaterThan(100);
  });

  it("no line break inside a paragraph or a list item (a paragraph and an item are one line)", () => {
    const found = all.filter((p) => !PENDING.some((x) => p.startsWith(x))).flatMap(wraps);
    expect(found, "join the lines: a paragraph and a list item are one line of any length (ADR-0046 п. 1)").toEqual([]);
  });

  it("no line address of a Markdown file — id, section or file instead", () => {
    const found = all.flatMap((p) => lineAddresses(read(p)).map((a) => `${p}:${a.line} ${a.ref}`));
    expect(found, "address a place by id → section → file, not by line number (ADR-0046 п. 2)").toEqual([]);
  });

  it("PENDING lists only paths that still have findings (ratchet)", () => {
    const clean = PENDING.filter((x) => all.filter((p) => p.startsWith(x)).flatMap(wraps).length === 0);
    expect(clean, "remove the clean path from PENDING").toEqual([]);
  });
});
